payum:
    security:
        token_storage:
            App\Entity\Payum\PaymentToken: { doctrine: orm }

    storages:
        App\Entity\Payum\Payment: { doctrine: orm }

    gateways:
        offline:
            factory: offline
        paypal_express_checkout:
            factory: paypal_rest
            client_id: '%env(PAYPAL_CLIENT_ID)%'
            client_secret: '%env(PAYPAL_CLIENT_SECRET)%'
            config_path: ~
            config:
                mode: '%env(PAYPAL_MODE)%'