framework:
  workflows:
    cart:
      type: 'state_machine'
      marking_store:
        type: 'method'
        property: 'place'
      supports:
        - App\Entity\Cart\Cart
      initial_marking: cart
      places:
        - cart
        - cancelled
        - pending
        - complete
      transitions:
        to_cancelled:
          from: [ cart,pending ]
          to: cancelled
        to_pending:
          from: [ pending,cart ]
          to: pending
        to_complete:
          from: [ pending ]
          to: complete
        reopen:
          from: [ cancelled ]
          to: cart

